[tls]
# cert_path = "./certs/example.com.pem"
# key_path  = "./certs/example.com.key"

[assets]
precompress = false
assets_dirs = ["./static/css", "./static/js", "./static/fonts"]
target_exts = ["css", "js", "woff", "woff2", "ttf", "otf"]
compression_types = ["br"]                                      # ["zst", "br", "gz"]
zstd_level = 3
brotli_quality = 11
gzip_level = 9

[security]
# allow_origins = [
#     "https://example.com",
#     "https://cloudflareinsights.com",
# ]
allow_origins = ["*"]
admin_password = "CHANGE_YOUR_PASSWORD"
admin_security_answers = ["default1", "default2", "default3"]
admin_security_questions = ["default1", "default2", "default3"]
auth_ext_secq = true
auth_ext_cftrace = false
cftrace_url = "example.com"
allowed_locs = ["CN", "US"]
csp_policy = """
default-src 'self'; \
script-src 'self'; \
style-src 'self' 'unsafe-inline'; \
img-src 'self' data:; \
connect-src 'self' https://cloudflare.com https://*.cloudflare.com; \
font-src 'self'; \
object-src 'none'; \
base-uri 'self'; \
form-action 'self'; \
frame-ancestors 'none'\
"""
permissions_policy = "camera=(), microphone=(), geolocation=(), payment=()"
