[profile]
current_identity = "Temp Page"
avatar_url = "/images/avatar.webp"
bg_url = "/images/bg.webp"
team_members = ["User_1", "User_2"]
site_version = "0.3.2-beta"
intro = "template."
note_url = "/note"
note_enable = true

[site]
index_title = "Lily Nest example - 梨窝"
meta_desc = "梨窝 meta example"
custom_head = """
<!-- <link rel="canonical" href="https://www.sulyhub.cn/{{url_path}}" /> -->
"""
footer_html = """
<a href="https://icp.gov.moe/?keyword=20260914" target="_blank">萌ICP备20260914号</a>
"""


[note]
note_title = "Lily Note - 梨记"
meta_desc = "梨窝的笔记列表 - 记录每一次进步 by Suly"
meta_keywords = "Suly, 梨记, 笔记, 博客, Rust"